# Generated by Django 3.0.6 on 2021-03-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Unique', models.IntegerField()),
                ('Quantie', models.IntegerField()),
                ('Montant', models.FloatField()),
                ('Commande_individu', models.CharField(max_length=1000)),
            ],
        ),
    ]
