# Generated by Django 3.1.7 on 2021-03-29 11:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Date_naissance', models.DateField()),
                ('numero_de_rue', models.DecimalField(decimal_places=3, default='', max_digits=3)),
                ('code_postal', models.DecimalField(decimal_places=5, default='', max_digits=5)),
                ('Ville', models.CharField(max_length=100)),
                ('Categorie_socioPro', models.CharField(choices=[('un', 'Etudiant'), ('deux', 'Cadre'), ('trois', 'Professeur')], max_length=100)),
                ('Numero_Telephone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantite', models.IntegerField()),
                ('Montant', models.FloatField()),
                ('Commande_article', models.CharField(max_length=1000)),
                ('client', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
            ],
        ),
    ]
