# Generated by Django 3.1.7 on 2021-03-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='Commande_individu',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='Type_commande',
        ),
    ]
