# Generated by Django 3.1.7 on 2021-03-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20210321_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='Numero_Unique',
        ),
    ]
