# Generated by Django 3.1.7 on 2021-03-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_commande_commande_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
