# Generated by Django 3.1.7 on 2021-04-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_auto_20210408_1800'),
        ('Pub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='destinataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.client'),
        ),
    ]
