# Generated by Django 3.1.7 on 2021-03-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_article', models.IntegerField()),
                ('nom_article', models.CharField(max_length=100)),
                ('quantite_article', models.IntegerField(default=0)),
            ],
        ),
    ]
