# Generated by Django 3.1.7 on 2021-03-29 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unique', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom_article', models.CharField(max_length=100)),
                ('quantite_article', models.IntegerField(default=0)),
            ],
        ),
    ]
