# Generated by Django 3.1.7 on 2021-03-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_auto_20210321_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='commande',
        ),
    ]
