# Generated by Django 3.1.7 on 2021-04-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_auto_20210412_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
