# Generated by Django 3.1.7 on 2021-04-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0007_auto_20210412_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
