# Generated by Django 3.1.7 on 2021-04-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0008_auto_20210412_1929'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='article',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='article',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
